version: "3"
services:
  apisix:
    image: apache/apisix:3.9.1-debian
    restart: always
    volumes:
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml
    environment:
      - APISIX_STAND_ALONE=true
      - APISIX_ENABLE_HOT_RELOAD=true
    command: ["sh", "-c", "apisix start -c /usr/local/apisix/conf/config.yaml"]
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"